# Generated by Django 5.0.1 on 2024-02-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notogrisoz',
            old_name='togri_soz',
            new_name='togriSoz',
        ),
    ]
